name: Pull Google Online Boutique Images and Deploy to ECR

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull, Tag, and Push Images to ECR
        run: |
          ACCOUNT_ID            = $(aws sts get-caller-identity --query "Account" --output text)

          EMAIL_IMAGE           = "us-central1-docker.pkg.dev/google-samples/microservices-demo/emailservice:v0.10.2"
          CHECKOUT_IMAGE        = "us-central1-docker.pkg.dev/google-samples/microservices-demo/checkoutservice:v0.10.2"
          RECOMMENDATION_IMAGE  = "us-central1-docker.pkg.dev/google-samples/microservices-demo/recommendationservice:v0.10.2"
          FRONTEND_IMAGE        = "us-central1-docker.pkg.dev/google-samples/microservices-demo/frontend:v0.10.2"
          PAYMENT_IMAGE         = "us-central1-docker.pkg.dev/google-samples/microservices-demo/paymentservice:v0.10.2"
          PRODUCT_CATALOG_IMAGE = "us-central1-docker.pkg.dev/google-samples/microservices-demo/productcatalogservice:v0.10.2"
          CARTSERVICE_IMAGE     = "us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice:v0.10.2"
          REDIS_IMAGE           = "redis:alpine"
          BUSYBOX_IMAGE         = "busybox:latest"
          LOADGEN_IMAGE         = "us-central1-docker.pkg.dev/google-samples/microservices-demo/loadgenerator:v0.10.2"
          CURRENCY_IMAGE        = "us-central1-docker.pkg.dev/google-samples/microservices-demo/currencyservice:v0.10.2"
          SHIPPING_IMAGE        = "us-central1-docker.pkg.dev/google-samples/microservices-demo/shippingservice:v0.10.2"
          AD_IMAGE              = "us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice:v0.10.2"

          # Please change the ECR names to match your repository names in Terraform

          EMAIL_ECR             = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/ky-tf-emailservice:v0.10.2"
          CHECKOUT_ECR          = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/ky-tf-checkoutservice:v0.10.2"
          RECOMMENDATION_ECR    = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/ky-tf-recommendationservice:v0.10.2"
          FRONTEND_ECR          = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/ky-tf-frontend:v0.10.2"
          PAYMENT_ECR           = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/ky-tf-paymentservice:v0.10.2"
          PRODUCT_CATALOG_ECR   = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/ky-tf-productcatalog:v0.10.2"
          CARTSERVICE_ECR       = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/ky-tf-cartservice:v0.10.2"
          REDIS_ECR             = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/ky-tf-redisalpine:alpine"
          BUSYBOX_ECR           = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/ky-tf-busybox:latest"
          LOADGEN_ECR           = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/ky-tf-loadgenerator:v0.10.2"
          CURRENCY_ECR          = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/ky-tf-currencyservice:v0.10.2"
          SHIPPING_ECR          = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/ky-tf-shippingservice:v0.10.2"
          AD_ECR                = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/ky-tf-adservice:v0.10.2"

          # Pull from Google Artifact Registry
          docker pull $EMAIL_IMAGE
          docker pull $CHECKOUT_IMAGE
          docker pull $RECOMMENDATION_IMAGE
          docker pull $FRONTEND_IMAGE
          docker pull $PAYMENT_IMAGE
          docker pull $PRODUCT_CATALOG_IMAGE
          docker pull $CARTSERVICE_IMAGE
          docker pull $REDIS_IMAGE
          docker pull $BUSYBOX_IMAGE
          docker pull $LOADGEN_IMAGE
          docker pull $CURRENCY_IMAGE
          docker pull $SHIPPING_IMAGE
          docker pull $AD_IMAGE

          # Tag for ECR
          docker tag $EMAIL_IMAGE $EMAIL_ECR
          docker tag $CHECKOUT_IMAGE $CHECKOUT_ECR
          docker tag $RECOMMENDATION_IMAGE $RECOMMENDATION_ECR
          docker tag $FRONTEND_IMAGE $FRONTEND_ECR
          docker tag $PAYMENT_IMAGE $PAYMENT_ECR
          docker tag $PRODUCT_CATALOG_IMAGE $PRODUCT_CATALOG_ECR
          docker tag $CARTSERVICE_IMAGE $CARTSERVICE_ECR
          docker tag $REDIS_IMAGE $REDIS_ECR
          docker tag $BUSYBOX_IMAGE $BUSYBOX_ECR
          docker tag $LOADGEN_IMAGE $LOADGEN_ECR
          docker tag $CURRENCY_IMAGE $CURRENCY_ECR
          docker tag $SHIPPING_IMAGE $SHIPPING_ECR
          docker tag $AD_IMAGE $AD_ECR


          # Push to ECR
          docker push $EMAIL_ECR
          docker push $CHECKOUT_ECR
          docker push $RECOMMENDATION_ECR
          docker push $FRONTEND_ECR
          docker push $PAYMENT_ECR
          docker push $PRODUCT_CATALOG_ECR
          docker push $CARTSERVICE_ECR
          docker push $REDIS_ECR
          docker push $BUSYBOX_ECR
          docker push $LOADGEN_ECR
          docker push $CURRENCY_ECR
          docker push $SHIPPING_ECR
          docker push $AD_ECR
