name: Pull Google Online Boutique Images and Deploy to ECR

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull, Tag, and Push Images to ECR
        shell: bash
        run: |
          set -e
          ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
          REGION=${AWS_REGION:-us-east-1} 

          declare -A boutique_services=(
            [emailservice]="v0.10.2"
            [checkoutservice]="v0.10.2"
            [recommendationservice]="v0.10.2"
            [frontend]="v0.10.2"
            [paymentservice]="v0.10.2"
            [productcatalogservice]="v0.10.2"
            [cartservice]="v0.10.2"
            [loadgenerator]="v0.10.2"
            [currencyservice]="v0.10.2"
            [shippingservice]="v0.10.2"
            [adservice]="v0.10.2"
          )

          for service in "${!boutique_services[@]}"; do
            version=${boutique_services[$service]}
            src="us-central1-docker.pkg.dev/google-samples/microservices-demo/${service}:${version}"
            dest="${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/ky-tf-${service}:${version}"

            echo "Processing $service..."
            docker pull "$src"
            docker tag "$src" "$dest"
            docker push "$dest"
          done

           # Handle redis and busybox
          declare -A misc_images=(
            [redis]="alpine"
            [busybox]="latest"
          )

          for name in "${!misc_images[@]}"; do
            tag="${misc_images[$name]}"
            src="${name}:${tag}"

            if [ "$name" == "redis" ]; then
              ecr_repo="ky-tf-redisalpine"
            else
              ecr_repo="ky-tf-${name}"
            fi

            dest="${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${ecr_repo}:${tag}"

            echo "Processing $name..."
            docker pull "$src"
            docker tag "$src" "$dest"
            docker push "$dest"
          done
